-- RODE ESSE SCRIPT NO 'SQL EDITOR' DO SUPABASE

create table feedbacks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  message text,
  rating integer,
  language text
);

-- HABILITAR RLS (Segurança)
alter table feedbacks enable row level security;

-- POLÍTICA 1: TODO MUNDO PODE LER (Public)
create policy "Enable read access for all users"
on "public"."feedbacks"
as PERMISSIVE
for SELECT
to public
using (true);

-- POLÍTICA 2: TODO MUNDO PODE CRIAR (Insert)
create policy "Enable insert for all users"
on "public"."feedbacks"
as PERMISSIVE
for INSERT
to public
with check (true);
